node{
    stage('SCM Checkout'){
        git 'https://github.com/haribabu-git/springboot1'    
    }
    stage('Compile-package'){
         def mvnHome = tool name: 'MAVEN_HOME', type: 'maven';
        bat "mvn package ${C:\\Program Files (x86)\\Jenkins\workspace\\springboot1\\}"
    }
    
}
